### ISSUE TITLE
Smarter algorithm to detect chocoblasts

### ISSUE THREAD

**Issue by fabmars** [Draluy/chocoratage#5]
2 examples: 
- someone typing "cho co"
- someone typing "c.h.o.c.o"
We should be able to detect those without resorting to complicated algorithms.

I propose to rework the KeyBuffer#containsIgnoreCase() and matching predicates:
- work from a stripped down version of what's typed, without spaces or punctuation or accents (might be related to #3 btw)
- not only work on the same amount of input words as those of the ForbiddenPhrases instances, but work on the sufficient amount of words to get a similar size (hence we may have to make a second try with one extra word if the letter count is not exact to this of the ForbiddenPhrase).

**Comment by Draluy** [comment]
I thought of this, but the solution is to simply put all letters ignoring any punctuation I think: "salutjameneleschocolatines" and then to search for forbidden words.

The algorithm to do that can be really computer intensive, so I stayed away from that, but I guess we dont really have a choice.

**Comment by Draluy** [comment]
Also, to speed up search times, maybe an implementation of a trie can be useful.

**Comment by fabmars** [comment]
@Draluy please assign this one to me.
