### ISSUE TITLE
Support AIX ?

### ISSUE THREAD

**Issue by fabmars** [Draluy/chocoratage#6]
I'm reading AIX 7.1 supports JDK8, so "Chocoratage" could in theory run on it.
https://wiki.openjdk.java.net/pages/viewpage.action?pageId=25329853

Though pretty much nothing modern runs on AIX, and certainly not workstations.

I'm reading on wikipedia it runs on CDE by default, so I4m suspecting the same locking mechanism as Solaris might do the job.
Testing would require getting our hands on a PowerPC machine, running AIX 7.1/7.2 on it, installing openjdk8 on it. I see some crazy folks have managed to emulate AIX on qemu, why not, but cleearly not a priority.
https://www.youtube.com/watch?v=e9hohbgO0Vs

**Comment by Draluy** [comment]
I would call it a day, you've done a great and extensive work already :)
