### ISSUE TITLE
Test on more OS versions

### ISSUE THREAD

**Issue by fabmars** [Draluy/chocoratage#7]
The current coverage (see OS.ods) is pretty wide across distributions and window managers, but most versions are recent. Could be worthwhile testig on:
- Ubuntu 14, 17
- Fedora older version (like from 3-4 years ago)
- Mandriva
- FreeBSD 10 if there is anOpenJDK port for it.
- Solaris 11 (required a Spectre-patched CPU)
- OSX, older, newer
- Windows 7

**Comment by fabmars** [comment]
@Draluy please assign this one to me.

**Comment by fabmars** [comment]
Old Ubuntus:
http://old-releases.ubuntu.com/releases/

oldest downloadable fedora: 29
https://dl.fedoraproject.org/pub/fedora/linux/releases/29/

Oldest  FreeBSD available is 11.2
https://download.freebsd.org/ftp/releases/ISO-IMAGES/11.2/FreeBSD-11.2-RELEASE-i386-disc1.iso

I still have an old Win7 license.

Solaris 11 refuses to install on my machine because it says my CPU isn't patched against Spectre...but it is.

As for OSX, I'll do what I can.

**Comment by fabmars** [comment]
So far
- Ubuntu 14, 17
- FreeBSD 11.2
- Windows 7
- OpenMandriva 4.0
all follow the existing patterns.

**Comment by fabmars** [comment]
Found Fedora Workstation 25, same as 31

**Comment by fabmars** [comment]
Tested on OSX Mountzain Lion (10.8.5), Maverick (10.9), Yosemite (10.10.5) and this is a pain in the neck: the locking command is now "/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend" (uppercase U on User.menu instead of lowercase on My Mojave 10.14). So now I'm trying to figure out in which version those animals changed the folder name. Judging by some commits I saw on github, it might be on High Sierra (10.13).
But its intaller wiped my harddisk before failing and all I have left is a bootable USB key with an uninstallable High Sierra. Working on it...

**Comment by Draluy** [comment]
What about launching both commands letting one silently fail and calling it a day?

**Comment by fabmars** [comment]
Nah :)
I managed to install High Sierra (10.13) and it's /User.menu/ (uppercase) too. So it gets lowercase from Mojave (10.14). Funnty thing, the partition I got on HS was case insensitive, so both commands worked.

**Comment by fabmars** [comment]
Got Solaris 11 to startup in VirtualBox thanks to https://docs.oracle.com/cd/E37838_01/html/E60973/instal.html

**Comment by fabmars** [comment]
OSX 10.15 Catalina is a piece of crap that's not unique in its kind only because Windows Vista existed before... the security layer makes it REAL hard to run any unsigned software from the terminal (or eslewhere for the matter) due to OSX security policies.
The Oracle JRE/JDK bundles just don't install (dmg, only applet plugin) or refuse to run (.tar). I managed to get OpenJDK 11 to run on it and in the end it's no different than the rest (/User.menu/) except that chocoratage will be virtually real hard to run from this OSX version...

**Comment by fabmars** [comment]
In the end:
* I reinstalled Mojave and realized the CGSession executable is "/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession" there too. Actually the path I'd used originally (with /user.menu lowercase) was a bad copy-paste and since the filesystem is case insensitive, it still worked. So, in the end I'm kindof dumb.
* Solaris 11 pkg solaris-desktop uses Gnome now so gnome-session-quit --no-prompt works but xlock too. And when switching to xterm, only xlock works, so we'll stick to it.

**Comment by fabmars** [comment]
Whilst working on the jnativehook build in https://github.com/Draluy/chocoratage/issues/3 I saw the lib only supports Linux, Windows and OSX.
So long for the FreeBSD support...
